// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

//go:build linux && !android

package dns

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"tailscale.com/health"
	"tailscale.com/types/logger"
)

const freshTomatoDNSFile = "/etc/dnsmasq-tailscale.conf"

type freshTomatoManager struct {
	logf   logger.Logf
	health *health.Tracker
}

func newFreshTomatoManager(logf logger.Logf, health *health.Tracker) OSConfigurator {
	return &freshTomatoManager{logf: logf, health: health}
}

func (m *freshTomatoManager) SetDNS(cfg OSConfig) error {
	if cfg.IsZero() {
		if err := os.Remove(freshTomatoDNSFile); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("freshtomato: removing dnsmasq config: %w", err)
		}
		m.logf("dns: freshtomato: removed %s", freshTomatoDNSFile)
		m.reloadDNSMasq()
		return nil
	}

	var lines []string
	for _, ns := range cfg.Nameservers {
		if len(cfg.SearchDomains) > 0 {
			for _, sd := range cfg.SearchDomains {
				lines = append(lines, fmt.Sprintf("server=/%s/%s", sd.WithoutTrailingDot(), ns))
			}
		} else {
			lines = append(lines, fmt.Sprintf("server=%s", ns))
		}
	}
	content := "# Generated by Tailscale - do not edit\n" + strings.Join(lines, "\n") + "\n"

	if err := os.WriteFile(freshTomatoDNSFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("freshtomato: writing dnsmasq config: %w", err)
	}
	m.logf("dns: freshtomato: wrote %s with %d server lines", freshTomatoDNSFile, len(lines))
	m.reloadDNSMasq()
	return nil
}

func (m *freshTomatoManager) reloadDNSMasq() {
	if err := exec.Command("killall", "-HUP", "dnsmasq").Run(); err != nil {
		m.logf("dns: freshtomato: dnsmasq HUP failed (%v), trying restart", err)
		if err2 := exec.Command("service", "dnsmasq", "restart").Run(); err2 != nil {
			m.logf("dns: freshtomato: dnsmasq restart also failed: %v", err2)
		}
	}
}

func (m *freshTomatoManager) SupportsSplitDNS() bool { return false }

func (m *freshTomatoManager) GetBaseConfig() (OSConfig, error) {
	return OSConfig{}, nil
}

func (m *freshTomatoManager) Close() error {
	if err := os.Remove(freshTomatoDNSFile); err != nil && !os.IsNotExist(err) {
		m.logf("dns: freshtomato: Close: remove %s: %v", freshTomatoDNSFile, err)
	}
	m.reloadDNSMasq()
	return nil
}
